#!/usr/bin/env bash
# generate the cms fixtures: a p-256 root, ed25519, p-256 and rsa-2048 leaves
# under it, and signed data from openssl for each algorithm
#
#   test/interop/generate.sh <dir>
#
# src/cms.mach embeds a set generated by this script. a fresh run makes new
# keys, so it only replaces those fixtures when they are regenerated on purpose
set -euo pipefail
dir=${1:?usage: generate.sh <dir>}
mkdir -p "$dir"
cd "$dir"

cat > leaf.cnf <<'CNF'
[leaf]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, nonRepudiation
extendedKeyUsage = emailProtection
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
CNF

openssl genpkey -quiet -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out root.key
openssl req -new -x509 -key root.key -subj "/C=US/O=Briar Test/CN=Briar Test CMS Root" \
    -days 3650 -sha256 -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" -out root.pem

openssl genpkey -quiet -algorithm ED25519 -out ed25519.key
openssl genpkey -quiet -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out p256.key
openssl genpkey -quiet -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out rsa.key
for name in ed25519 p256 rsa; do
    openssl req -new -key "$name.key" -subj "/C=US/O=Briar Test/CN=Briar Test CMS $name" \
        -out "$name.csr"
    openssl x509 -req -in "$name.csr" -CA root.pem -CAkey root.key -days 3650 -sha256 \
        -extfile leaf.cnf -extensions leaf -out "$name.pem" 2>/dev/null
    cat "$name.pem" root.pem > "$name-chain.pem"
done

printf 'mach-pki cms interop\n' > content.txt
sign() { openssl cms -sign -binary -in content.txt -outform DER "$@"; }
sign -signer ed25519.pem -inkey ed25519.key -md sha512 -cades -out openssl-ed25519-detached.der
sign -signer p256.pem -inkey p256.key -nodetach -out openssl-p256-attached.der
sign -signer rsa.pem -inkey rsa.key -out openssl-rsa-pkcs1-detached.der
sign -signer rsa.pem -inkey rsa.key -nodetach -md sha384 -keyopt rsa_padding_mode:pss \
    -keyopt rsa_pss_saltlen:digest -out openssl-rsa-pss384-attached.der
