#!/usr/bin/env bash
# generate the digest and curve fixtures: p-384 with sha-256, p-521 with sha-512
# and rsa with sha-512 in both paddings, each a root and a leaf with openssl
# cms signed data under it, and sha-1 leaves for the weak algorithm checks
#
#   test/interop/generate-digests.sh <dir>
#
# src/verify.mach and src/cms.mach embed a set generated by this script. a
# fresh run makes new keys, so it only replaces those fixtures when they are
# regenerated on purpose
set -euo pipefail
dir=${1:?usage: generate-digests.sh <dir>}
mkdir -p "$dir"
cd "$dir"

cat > leaf.cnf <<'CNF'
[leaf]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, nonRepudiation
extendedKeyUsage = emailProtection
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
CNF

# root <name> <genpkey options> <digest> [sigopt...]: a self-signed root
root() {
    local name=$1 keyopts=$2 md=$3
    shift 3
    openssl genpkey -quiet $keyopts -out "$name-root.key"
    openssl req -new -x509 -key "$name-root.key" -subj "/C=US/O=Briar Test/CN=Briar Test $name Root" \
        -days 3650 "-$md" "$@" -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" -out "$name-root.pem"
    openssl x509 -in "$name-root.pem" -outform DER -out "$name-root.der"
}

# leaf <name> <root> <digest> [sigopt...]: a leaf under a root, its key made once
leaf() {
    local name=$1 root=$2 md=$3
    shift 3
    openssl req -new -key "$name.key" -subj "/C=US/O=Briar Test/CN=Briar Test $name" -out "$name.csr"
    openssl x509 -req -in "$name.csr" -CA "$root-root.pem" -CAkey "$root-root.key" -days 3650 \
        "-$md" "$@" -extfile leaf.cnf -extensions leaf -out "$name.pem" 2>/dev/null
    openssl x509 -in "$name.pem" -outform DER -out "$name.der"
}

root p384 "-algorithm EC -pkeyopt ec_paramgen_curve:P-384" sha256
openssl genpkey -quiet -algorithm EC -pkeyopt ec_paramgen_curve:P-384 -out p384.key
leaf p384 p384 sha256

root p521 "-algorithm EC -pkeyopt ec_paramgen_curve:P-521" sha512
openssl genpkey -quiet -algorithm EC -pkeyopt ec_paramgen_curve:P-521 -out p521.key
leaf p521 p521 sha512

root rsa "-algorithm RSA -pkeyopt rsa_keygen_bits:2048" sha512
openssl genpkey -quiet -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out rsa.key
cp rsa.key rsa-pss.key
leaf rsa rsa sha512
leaf rsa-pss rsa sha512 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:digest

# sha-1 leaves, by an rsa root and by a p-384 root
cp rsa.key rsa-sha1.key
leaf rsa-sha1 rsa sha1
cp p384.key p384-sha1.key
leaf p384-sha1 p384 sha1

printf 'mach-pki cms interop\n' > content.txt
sign() { openssl cms -sign -binary -in content.txt -outform DER -nodetach "$@"; }
sign -signer p384.pem -inkey p384.key -md sha256 -out openssl-p384-sha256-attached.der
sign -signer p521.pem -inkey p521.key -md sha512 -out openssl-p521-sha512-attached.der
sign -signer rsa.pem -inkey rsa.key -md sha512 -out openssl-rsa-pkcs1-sha512-attached.der
sign -signer rsa-pss.pem -inkey rsa-pss.key -md sha512 -keyopt rsa_padding_mode:pss \
    -keyopt rsa_pss_saltlen:digest -out openssl-rsa-pss-sha512-attached.der
